services:

  api:
    build: .

    ports:
      - "8000:8000"

    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8000/health/ready > /dev/null 2>&1 || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 5
